# Generated by Django 4.2.16 on 2024-10-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="estimated_time",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
